### ISSUE TITLE
Error in ipm get agt

### ISSUE THREAD

**Issue by exrajat** [fsilveir/ipm-cli#7]
Hello Felipe,

We are facing issue with ipm-cli tool. Please find the error-

[exrajat@apmsao01p01 ~]$ ipm get agt
'agent_name','hostname','product_code','description','version','status'
Traceback (most recent call last):
  File "/tivrepos/scripts/ipm-cli-master/ipm-cli/ipm.py", line 314, in get_agents
    "parentNode", \
KeyError: 'keyIndexName'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tivrepos/scripts/ipm-cli-master/ipm-cli/ipm.py", line 1249, in <module>
  File "/tivrepos/scripts/ipm-cli-master/ipm-cli/ipm.py", line 1217, in main
  File "/tivrepos/scripts/ipm-cli-master/ipm-cli/ipm.py", line 323, in get_agents
    def set_payload(href,session_type,rg_identification, rg_description):
KeyError: 'online'
[exrajat@apmsao01p01 ~]$

**Comment by fsilveir** [comment]
Hi @exrajat thanks for reporting the issue. I was able to replicate the problem, and fixed it for me  on release [0.5.0](https://github.com/fsilveir/ipm-cli/releases/tag/v0.5.0), please check and let me know if you're still experiencing the same issue.

**Comment by fsilveir** [comment]
@exrajat actually there's no relation to the list of supported agents in this case, since the script just prints the information provided by the API -- in your case, it seems your IPM subscription is not passing values to the `keyIndexName` field related to the agent name for some reason... these entries are probably related to old agents that are not connected for a long time or for some reason might have failed to be properly cleared by the IPM itself.

Anyway, I've included another step to exclude entries from the output when the agent name is `unknown`, since there's no point printing an empty entries ;-)

 Please test with [v.0.5.1](https://github.com/fsilveir/ipm-cli/tree/v0.5.1) and let me know.
